// Code generated by hertztool.

package main

import (
	"a.com/b/c/biz/handler"
	"code.byted.org/middleware/hertz/byted"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

func main() {
	byted.Init()
	r := byted.Default()

	r.GET("/ppp", handler.Ping)
	handler.Ping(context.Background(), &app.RequestContext{})

	register(r)
	r.Spin()
}
