// Code generated by hertztool. DO NOT EDIT.

package main

import (
	router "a.com/b/c/biz/router"
	"code.byted.org/middleware/hertz/pkg/app/server"
)

// register registers all routers.
func register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)

}
