// Code generated by hertztool

package main

import (
	handler "a.com/b/c/biz/handler"
	"code.byted.org/middleware/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
