// Code generated by hertztool. DO NOT EDIT.

package router

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
}
